# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: org
    displayName: org
    type: string
    default: org1
    values: 
    - org1
    - org2
    - org3
  - name: process
    displayName: process
    type: string
    default: My Test
    values:
    - My Test
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: >-
            test -ntp
            "-Dprocess=${{parameters.process}}"
            -Dorg=${{parameters.org}}


